export const translations = {
  en: {
    greeting: 'Hi, Valentyn Starushok', intro: 'Thank you for using our service. Below you will find all the relevant details about your parcel, including information on how to make a payment for customs and VAT.',
    senderInfo:'Sender Information', parcelNumber:'Parcel number', senderName:"Sender's Name", senderSurname:"Sender's Surname", senderCountry:"Sender's Country",
    shipmentQuestion:'Is this shipment for a private individual or a company?', privateTitle:'I am an individual (private parcel)', privateDesc:'Personal shipment with standard processing', companyTitle:'I represent a company (commercial shipment)', companyDesc:'Customs clearance for commercial parcels must be arranged directly with our partner.',
    fillInfo:'Please fill out the following information to complete customs clearance for your package:', firstName:'First Name', surname:'Surname', idNumber:'Identification Number (ID Card Number or Passport Number)', phone:'Contact Phone Number', email:'Email Address',
    purchasedGift:'Purchased / Gift', purchase:'Purchase', purchaseDesc:'Items that were purchased (requires invoice/receipt)', gift:'Gift', giftDesc:'Items sent as a gift (no documentation required)', upload:'Upload Invoice / Receipt', drag:'Drag and drop files here or', browse:'browse', formats:'Accepted formats: PDF, PNG, JPG', limits:'Allowed up to 10 files, each up to 10MB',
    customsStatement:'Statement For Customs Declaration', showItem:'Show item', typeGoods:'Type of goods', amount:'Amount', totalValue:'Total value', charges:'The following customs and VAT charges have been calculated for your parcel:', customsDuty:'Customs Duty', vat:'VAT', brokerage:'Brokerage Commission', totalPayable:'Total Payable',
    terms:'Terms and Conditions', personalBefore:'I agree to ', personalLink:'the processing of my personal data', personalAfter:' for the purpose of customs clearance.', authorizeBefore:'I hereby authorize Karex Paczka sp. Z o.o. to make decisions as a customs agent by signing ', authorizeLink:'authorization to act as a direct agent', authorizeAfter:'.', parcelConfirm:'I confirm that the contents of the package are not returned goods, are not subject to temporary clearance, and are not resettlement property.',
    review:'Please Review and Sign', signP1:'By signing below, you confirm that the information provided is accurate and complete. You also agree to the terms outlined, including the processing of your personal data for customs clearance and authorization of Karex Paczka sp. Z o.o. as your direct agent in this process.', signP2a:'To sign, please ', signDraw:'draw your signature', signP2b:' using your ', signFinger:'finger', signOr:' or ', signStylus:'stylus', signEnd:' in the designated area below.', continue:'CONTINUE TO PAYMENT', signaturePreview:'Signature Preview:',
    commercialDetected:'Commercial Shipment Detected', commercialDesc:'Customs clearance for commercial parcels must be arranged directly with our partner agency. Please contact them using the information below to proceed with your shipment.', phoneSupport:'Phone Support', emailSupport:'Email Support', officeAddress:'Office Address', response24:'Response within 24 hours', submitBroker:'Submit and Contact Broker', poland:'Poland',
    errFirst:'Valid first name is required.', errSurname:'Valid surname is required.', errId:'Please enter a valid ID Card Number.', errPhone:'Phone number is required.', errPhoneLen:'Invalid phone number length', errEmail:'Please enter a valid email address.', errPurchase:'Please select either Purchase or Gift.', errFileMin:'Please upload at least one file.', errFileMax:'Allowed up to 10 files.', errSignature:'Signature is required.', errPersonal:'You must agree to personal data processing.', errAuthorize:'You must authorize the direct agent.', errParcel:'You must confirm the parcel content.'
  },
  pl: {
    greeting: 'Cześć, Valentyn Starushok', intro: 'Dziękujemy za skorzystanie z naszych usług. Poniżej znajdziesz wszystkie istotne informacje dotyczące Twojej przesyłki, w tym informacje o sposobie opłacenia należności celnych i VAT.',
    senderInfo:'Informacje o nadawcy', parcelNumber:'Numer przesyłki', senderName:'Imię nadawcy', senderSurname:'Nazwisko nadawcy', senderCountry:'Kraj nadawcy',
    shipmentQuestion:'Czy przesyłka jest przeznaczona dla osoby prywatnej czy firmy?', privateTitle:'Jestem osobą prywatną (przesyłka prywatna)', privateDesc:'Przesyłka prywatna ze standardową obsługą', companyTitle:'Reprezentuję firmę (przesyłka handlowa)', companyDesc:'Odprawę celną przesyłek handlowych należy uzgodnić bezpośrednio z naszym partnerem.',
    fillInfo:'Wypełnij poniższe dane, aby zakończyć odprawę celną przesyłki:', firstName:'Imię', surname:'Nazwisko', idNumber:'Numer identyfikacyjny (numer dowodu osobistego lub paszportu)', phone:'Numer telefonu kontaktowego', email:'Adres e-mail',
    purchasedGift:'Zakup / Prezent', purchase:'Zakup', purchaseDesc:'Zakupione przedmioty (wymagana faktura/paragon)', gift:'Prezent', giftDesc:'Przedmioty wysłane jako prezent (dokumenty nie są wymagane)', upload:'Prześlij fakturę / paragon', drag:'Przeciągnij i upuść pliki tutaj lub', browse:'wybierz pliki', formats:'Akceptowane formaty: PDF, PNG, JPG', limits:'Maksymalnie 10 plików, każdy do 10 MB',
    customsStatement:'Oświadczenie do zgłoszenia celnego', showItem:'Pokaż pozycję', typeGoods:'Rodzaj towaru', amount:'Ilość', totalValue:'Łączna wartość', charges:'Dla Twojej przesyłki obliczono następujące należności celne i VAT:', customsDuty:'Cło', vat:'VAT', brokerage:'Prowizja agencji celnej', totalPayable:'Łącznie do zapłaty',
    terms:'Warunki i zgody', personalBefore:'Wyrażam zgodę na ', personalLink:'przetwarzanie moich danych osobowych', personalAfter:' w celu dokonania odprawy celnej.', authorizeBefore:'Niniejszym upoważniam Karex Paczka sp. z o.o. do działania jako przedstawiciel celny poprzez podpisanie ', authorizeLink:'upoważnienia do działania w charakterze przedstawiciela bezpośredniego', authorizeAfter:'.', parcelConfirm:'Potwierdzam, że zawartość przesyłki nie stanowi towarów zwracanych, nie podlega odprawie czasowej ani nie jest mieniem przesiedleńczym.',
    review:'Sprawdź dane i podpisz', signP1:'Podpisując poniżej, potwierdzasz, że podane informacje są prawidłowe i kompletne. Akceptujesz również wskazane warunki, w tym przetwarzanie danych osobowych w celu odprawy celnej oraz upoważnienie Karex Paczka sp. z o.o. do działania jako przedstawiciel bezpośredni.', signP2a:'Aby podpisać, ', signDraw:'narysuj swój podpis', signP2b:' za pomocą ', signFinger:'palca', signOr:' lub ', signStylus:'rysika', signEnd:' w wyznaczonym polu poniżej.', continue:'PRZEJDŹ DO PŁATNOŚCI', signaturePreview:'Podgląd podpisu:',
    commercialDetected:'Wykryto przesyłkę handlową', commercialDesc:'Odprawę celną przesyłek handlowych należy uzgodnić bezpośrednio z naszą partnerską agencją. Skontaktuj się z nią, korzystając z poniższych danych.', phoneSupport:'Wsparcie telefoniczne', emailSupport:'Wsparcie e-mail', officeAddress:'Adres biura', response24:'Odpowiedź w ciągu 24 godzin', submitBroker:'Wyślij i skontaktuj się z agentem', poland:'Polska',
    errFirst:'Wprowadź prawidłowe imię.', errSurname:'Wprowadź prawidłowe nazwisko.', errId:'Wprowadź prawidłowy numer dowodu osobistego lub paszportu.', errPhone:'Numer telefonu jest wymagany.', errPhoneLen:'Nieprawidłowa długość numeru telefonu', errEmail:'Wprowadź prawidłowy adres e-mail.', errPurchase:'Wybierz Zakup lub Prezent.', errFileMin:'Prześlij co najmniej jeden plik.', errFileMax:'Dozwolone jest maksymalnie 10 plików.', errSignature:'Podpis jest wymagany.', errPersonal:'Musisz wyrazić zgodę na przetwarzanie danych osobowych.', errAuthorize:'Musisz udzielić upoważnienia przedstawicielowi bezpośredniemu.', errParcel:'Musisz potwierdzić zawartość przesyłki.'
  }
};
